name: final_project
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  easy_localization: ^3.0.7
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.2.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  onesignal_flutter: ^5.3.3
  skeletonizer: ^2.0.1
  smooth_page_indicator: ^1.2.1
  table_calendar: ^3.2.0
  google_maps_flutter: ^2.12.3
  
  


  cupertino_icons: ^1.0.8
  flutter_chat_core: ^2.6.1
  flutter_chat_ui: ^2.5.2
  flutter_switch: ^0.3.2
  fl_chart: ^1.0.0
  dart_mappable: ^4.5.0
  pinput: ^5.0.1
  slide_countdown: ^2.0.2
  image_picker: ^1.1.2
  moyasar: ^2.0.18


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  dart_mappable_builder: ^4.5.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - .env
